name: Deploy MkDocs

on:
  push:
    tags:
      - "*"
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build-mk-docs:
    uses: ynput/ops-repo-automation/.github/workflows/deploy_mkdocs.yml@main
    with:
      repo: ${{ github.repository }}
    secrets:
      YNPUT_BOT_TOKEN: ${{ secrets.YNPUT_BOT_TOKEN }}
      CI_USER: ${{ secrets.CI_USER }}
      CI_EMAIL: ${{ secrets.CI_EMAIL }}
